name: "size-limit"

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  actions: write       # Necessary to cancel workflow executions
  checks: write        # Necessary to write reports

jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v4
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
