name: test

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        # Use the same Node.js version as specified in your .nvmrc file
        node-version-file: '.nvmrc'

    - name: Install dependencies
      run: npm install

    - name: Run linters
      run: npm run lint

    - name: Run tests
      run: npm test
